name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
              toolchain: nightly
              components: clippy, rustfmt
              override: true

      - name: Install udev
        run: sudo apt-get install udev

      - name: Install libudev-dev
        run: sudo apt-get install libudev-dev

      - name: RustFmt
        uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
              
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            args: --all-features
            
      - name: Run tests
        run: cargo test --verbose
